version: 2.1
orbs:
  node: circleci/node@4.9.0
  docker: circleci/docker@0.5.19
jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:202010-01 # recommended linux image
    steps:
      - checkout
      - node/install:
          node-version: '16.13.1'
      - docker/install-docker
      - run: node --version
      - run: npm --version
      - run: docker --version
      - run: env
      - node/install-packages
      - run: npm install --no-save tap-xunit
      - run:
          name: spinning up ganache
          command: npm run start:eth
          background: true
      - run: mkdir -p _out/unit _out/e2e
      #- run: npm test --  --timeout=5m --tap| npx tap-xunit > _out/unit/test.xml
      - run: npm test --  --timeout=5m --tap --no-color > _out/unit/test.xml
      - run: npm run build
      - run: npm run test:e2e --  --timeout=10m --tap| npx tap-xunit > _out/e2e/test.xml
      #- run: npm run test:e2e --  --timeout=10m --tap --no-color| npx tap-xunit > _out/e2e/test.xml
      - store_test_results:
          path: _out
      - store_artifacts:
          path: _out

  build-and-release-to-staging:
    machine:
      image: ubuntu-2004:202010-01 # recommended linux image
    steps:
      - checkout
      - node/install:
          node-version: '16.13.1'
      - docker/install-docker
      - run: ./boyar/create-version-file.sh
      - node/install-packages
      - run: ./boyar/docker-build.sh
      - run: ./.circleci/release-to-staging.sh

  build-and-release:
    machine:
      image: ubuntu-2004:202010-01 # recommended linux image
    steps:
      - checkout
      - node/install:
          node-version: '16.13.1'
      - docker/install-docker
      - run: ./boyar/create-version-file.sh
      - node/install-packages
      - run: ./boyar/docker-build.sh
      - run: ./.circleci/release.sh

workflows:
  build-and-test:
    jobs:
      - build-and-test
      - build-and-release-to-staging:
          filters:
            branches:
              only: /.*/
            tags:
              only: /v.*/
