version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '12.13.0'
    steps:
      - setup_remote_docker
      - checkout
      - run: cat $BASH_ENV
      - run: node --version
      - run: npm --version
      - run: docker --version
      - run: env
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: npm run build
            - run: npm run test:e2e -- --timeout=1m

workflows:
    build-and-test:
      jobs:
        - build-and-test